# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'EJPhotoStorage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EJPhotoStorage
  pod 'CHTCollectionViewWaterfallLayout/Swift'
  
  target 'EJPhotoStorageTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
